version: 2.1

orbs:
  pfe: pantheon-systems/front-end@0.4.0
  queue: eddiewebb/queue@1.5.0

workflows:
  build-preview-test-deploy:
    jobs:
      - pfe/gatsby-build-and-deploy:
          use-yarn: false
          deployment-path: docs
          # https://circleci.com/docs/2.0/configuration-reference/#docker-executor
          # https://github.com/pantheon-systems/frontend-orbs#parameters
          resource-class: small
          incremental-build: true
          gatsby-cache-version: "v1.8.23"
          pre-steps:
            - checkout
            - run:
                name: Import External Data
                command: .circleci/scripts/import-external-data.sh
