name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          merge-message: |
            Thanks for contributing to the Pantheon Docs site! You've earned a [Docs sticker](https://get.printfection.com/hkxgd/9219758888)!
          pr-message: |
            Your first contribution to Pantheon Docs!